### ISSUE TITLE
simple_plot_ppi() got multiple values for argument 'cmap'

### ISSUE THREAD

**Issue by abanger** [YvZheng/pycwr#11]
examples/pycwr_example.ipynb

RadarGraph.simple_plot_ppi(dbz_test.range, dbz_test.azimuth, dbz_test.elevation,dbz_test, cmap="CN_ref", normvar=(-5,75))
TypeError: simple_plot_ppi() got multiple values for argument 'cmap'

**Comment by YvZheng** [comment]
@abanger I have fixed this bugs and update jupyter exmaple, now you can try in version 0.2.13. But I recommend you adopt the drawing method in README.md. #11
