### ISSUE TITLE
转换位pyart格式的时候缺少“ncp”变量

### ISSUE THREAD

**Issue by wanghui0225** [YvZheng/pycwr#15]
缺少ncp--normalized_coherent_power'应该是国内的SQI，还有使用radar = radar.extract_sweeps([0])，这个命令出错

**Comment by YvZheng** [comment]
@wanghui0225 可以麻烦将出错的数据附上吗？ 以便我排查错误，请发送至我的邮箱YuZheng1206@outlook.com

**Comment by YvZheng** [comment]
#15已修复转换格式问题
