### ISSUE TITLE
【求助极坐标转直角坐标】

### ISSUE THREAD

**Issue by dreaming-coder** [YvZheng/pycwr#24]
你好，我想问一下，有什么方法能将雷达的径向数据转成直角坐标吗，就是CAPPI那样，我不是气象专业的，不太懂具体的转换方法，现在做雷达外推需要CAPPI这种直角坐标的数据

**Comment by bugsuse** [comment]
@dreaming-coder  可以查看`transforms.py` 中的相关函数 https://github.com/YvZheng/pycwr/blob/fe5b86c3267697f3d3b9584eecd12fb4f61c8684/pycwr/core/transforms.py#L50
https://github.com/YvZheng/pycwr/blob/fe5b86c3267697f3d3b9584eecd12fb4f61c8684/pycwr/core/transforms.py#L95-L104

**Comment by dreaming-coder** [comment]
@bugsuse 是不是只能一个个输入仰角，方向角，半径的数据转换坐标系，然后转出来的点不是规整的格点数据啊？

**Comment by bugsuse** [comment]
@dreaming-coder 可以使用数组的形式，把格点到雷达的距离，方位角和仰角提供给函数直接转换，输出的就是网格信息了
