### ISSUE TITLE
安装错误：proj没有安装

### ISSUE THREAD

**Issue by Syize** [YvZheng/pycwr#27]
直接通过pip安装会提示没有安装Proj 4.9.0，而通过pip安装proj只能找到0.2.0版本的
建议修改一下README

**Comment by Syize** [comment]
系统是Ubuntu20.04，pip版本20.0.2

**Comment by Syize** [comment]
通过以下方法解决：
`apt install libproj-dev proj-data proj-bin`
`apt install libgeos-dev`
`pip install cartopy`
`pip install pycwr`

**Comment by YvZheng** [comment]
安装readme安装，使用conda install cartopy -c conda-forge
然后再执行pip install pycwr
