### ISSUE TITLE
如何得到组合反射率、CAPPI等计算参数的经纬度 坐标信息

### ISSUE THREAD

**Issue by holagony** [YvZheng/pycwr#28]
您好！想请问下如何获取组合反射率、CAPPI等参数的坐标信息呢？我想输出为二维数据用于回波外推使用，十分感谢！

**Comment by zxdawn** [comment]
@holagony 参考画图脚本里的[self.Radar.add_product_CR_lonlat](https://github.com/YvZheng/pycwr/blob/5109f0e3ec35b31f4cf155c0286cea7e5108b580/pycwr/draw/RadarPlot.py#L454-L456)和[self.Radar.add_product_CAPPI_lonlat](https://github.com/YvZheng/pycwr/blob/5109f0e3ec35b31f4cf155c0286cea7e5108b580/pycwr/draw/RadarPlot.py#L384-L386)
