### ISSUE TITLE
How to remove the legend and border?

### ISSUE THREAD

**Issue by afunnyrainman** [YvZheng/pycwr#29]
How to remove the legend and border?

**Comment by cmaMrSober** [comment]
ax.spines['right'].set_color('none')
ax.spines['top'].set_color('none')
ax.spines['left'].set_color('none')
ax.spines['bottom'].set_color('none')
ax.set_xticks([])
ax.set_yticks([])

**Comment by cmaMrSober** [comment]
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)
ax.spines['left'].set_visible(False)
ax.spines['bottom'].set_visible(False)
ax.set_xticks([])
ax.set_yticks([])

**Comment by afunnyrainman** [comment]
谢谢,think you .
