### ISSUE TITLE
请问怎么循环绘制

### ISSUE THREAD

**Issue by afunnyrainman** [YvZheng/pycwr#31]
比如我只去0-40DBZ的数据，40-50DBZ的数据，数据确定是对应区间的，但是出来的颜色却明显不是应该有的颜色。。。。。

**Comment by afunnyrainman** [comment]
我是使用plt.savefig将图片存储到本地的。

**Comment by YvZheng** [comment]
能把代码和结果贴出来吗？

**Comment by afunnyrainman** [comment]
请教了别人，已经解决了。谢谢
