### ISSUE TITLE
画出来的图有些失真是怎么回事

### ISSUE THREAD

**Issue by dingxiaodong0307** [YvZheng/pycwr#34]
请教一下老师，用这个包画出来的图有失真现象，例如没有径向辐合，而实际是有的（小时雨强160+），这是怎么回事呀？
数据是C波段双偏振雷达基数据。（Z9095.AR2格式）

**Comment by YvZheng** [comment]
可尝试换一下colormap，有些径向辐合的尺度比较小

**Comment by dingxiaodong0307** [comment]
确实是尺度比较小，cc特征也没有显示。请问这要怎么换，修改colormap文件吗，还是直接把这个文件更换掉，暂时找不到合适的。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yu Zheng ***@***.***&gt;
发送时间: 2021年9月4日 13:06
收件人: YvZheng/pycwr ***@***.***&gt;
抄送: dingxiaodong0307 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[YvZheng/pycwr] 画出来的图有些失真是怎么回事 (#34)





 
可尝试换一下colormap，有些径向辐合的尺度比较小
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
