### ISSUE TITLE
请问能否将pyart读取后的 Radar 对象转换为 PRD 对象？

### ISSUE THREAD

**Issue by kM-Stone** [YvZheng/pycwr#38]
我已经使用 PyArt 成功读取数据为PyartRadar.Radar对象，但现在希望使用 pycwr 进行一些处理，请问我该如何将这个 PyartRadar.Radar 对象转换为 PRD 对象呢？ 只能自己另写一个接口吗
我看了 pycwr 的文档，似乎只有读取几类雷达数据格式，以及将PRD对象转化为 Radar对象的方法

**Comment by YvZheng** [comment]
暂时没有此功能
