### ISSUE TITLE
基数据等经纬度网格化问题

### ISSUE THREAD

**Issue by xinzhuang** [YvZheng/pycwr#40]
您好，对于读取的PRD数据中dBZ产品，dim为 time ,range，如何转换为等经纬度间隔比如0.01度的dBZ DataArray呢？我尝试使用pycwr\interp\RadarInterp.py 中radar_interp2d函数，这个函数处理的似乎是 笛卡尔坐标系xyz,对于经纬度坐标是否适合呢，是否有相应解决办法呢？

**Comment by YvZheng** [comment]
可以将经纬度转化为x y，再插值到对应x， y上
