### ISSUE TITLE
一个体扫 一个仰角一个数据文件的方式 进行读取解析数据文件报错，正确的说应该是转prd报错

### ISSUE THREAD

**Issue by dltjiangfeipeng** [YvZheng/pycwr#43]
一个体扫 一个仰角一个数据文件的方式 进行读取解析数据文件报错，正确的说应该是转prd报错
![image](https://user-images.githubusercontent.com/30610103/223633398-c98beab1-a9b1-4d47-af05-94cdc8bac0bf.png)

**Comment by YvZheng** [comment]
pycwr 3.6.0 has fixed this bug
