### ISSUE TITLE
关于安装的问题

### ISSUE THREAD

**Issue by FOR-BANANA** [YvZheng/pycwr#46]
安装完后，在导入时问题报错：“ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()”
![IMG_3420](https://github.com/YvZheng/pycwr/assets/47943622/45609fb4-f099-4131-ac0f-f89d1df10931)

**Comment by FOR-BANANA** [comment]
请问这个要如何解决？

**Comment by gf1023456** [comment]
同遇到，解决了吗

**Comment by gf1023456** [comment]
> 

pycwr 包中的 cm_colorblind.py 文件的第 63 行。有误 你将那个if改为   if np.any([x == 'red' for x in spec]):  这样就能用了

**Comment by YvZheng** [comment]
I installed pycwr 3.6.0 based on python3.11 and found no errors. Can you provide me with specific environment information? @FOR-BANANA @gf1023456 
![image](https://github.com/YvZheng/pycwr/assets/34502899/baf6c790-ed16-4bca-b960-607ffc4ce70d)

**Comment by Qxaqq** [comment]
请帮忙指导一下
![image](https://github.com/YvZheng/pycwr/assets/141794581/b2a8eaab-6de8-4549-86ac-c799ec88b639)

**Comment by gf1023456** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Qxaqq** [comment]
> 请帮忙指导一下 ![image](https://user-images.githubusercontent.com/141794581/271153176-b2a8eaab-6de8-4549-86ac-c799ec88b639.png)

已解决，按照Pull requests里的修改，3处if 'red' in spec:改为 if np.any([x == 'red' for x in spec]):

**Comment by Syize** [comment]
> I installed pycwr 0.3.6 based on python3.11 and found no errors. Can you provide me with specific environment information? @FOR-BANANA @gf1023456 ![image](https://private-user-images.githubusercontent.com/34502899/262611824-baf6c790-ed16-4bca-b960-607ffc4ce70d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTg5OTcsIm5iZiI6MTcxNDk5ODY5NywicGF0aCI6Ii8zNDUwMjg5OS8yNjI2MTE4MjQtYmFmNmM3OTAtZWQxNi00YmNhLWI5NjAtNjA3ZmZjNGNlNzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEyMzEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNmUwZTQ4OTE0NDk3MjI3MTYyOTAwNjRlNzViOGEwNDZiOTkxZGY2MTRhYjUxYjZiMjM1YzVlMjQwMmQ2OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pSHH1_qbRYqFa2dIGRi_4iC7-UbkA8frlIyKC861f20)

This error happens because the type of variable `spec` changes several times. By adding `print(spec)` we can see the type of `spec` can be:

```
<class 'dict'>
<class 'numpy.ndarray'>
<class 'list'>
```
and the error raises when the type of `spec` is `list`.

**Comment by gf1023456** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by YvZheng** [comment]
This problem has been fixed in version 0.4.0
