### ISSUE TITLE
Add support of Composite Reflectivity (CRF)

### ISSUE THREAD

**Issue by zxdawn** [YvZheng/pycwr#5]
I've added that to `pyart` last year ...
But, they haven't merged [that](https://github.com/ARM-DOE/pyart/pull/745).
Maybe they forgot that, I will remind them after Thanksgiving Day :)

Should we add that function to `pycwr`?

**Comment by bugsuse** [comment]
Good idea! You can merge the function into `pycwr`! @zxdawn

**Comment by YvZheng** [comment]
时经三个月我终于要关闭这个issue了，已更新组合反射率计算，cython加速，计算耗时约2s。#5

**Comment by zxdawn** [comment]
@YvZheng 哈，66666。这个还在我的计划列表没动呢😂
