### ISSUE TITLE
Wrong version of netcdf4

### ISSUE THREAD

**Issue by zxdawn** [YvZheng/pycwr#7]
The newest version of netcdf4 from [anaconda channel](https://anaconda.org/anaconda/netcdf4) is 1.4.2.

https://github.com/YvZheng/pycwr/blob/7459371588e6d0d6d0737e249afa3921fe073151/setup.py#L18

`1.5.2` should be replaced by `1.4.2` or lower version.

**Comment by bugsuse** [comment]
The newest version from pypi is 1.5.3. Closed. @zxdawn

**Comment by zxdawn** [comment]
@bugsuse It's better to open this again and test lower version.

Otherwise, users using anaconda would get the error.

**Comment by YvZheng** [comment]
have updated requirements.txt and setup.py
